spring.application.name=service-login
server.port= 9100
#\u7F16\u5199nacos \u670D\u52A1\u542F\u52A8\u7684\u6CE8\u518C\u5730\u5740
spring.cloud.nacos.server-addr= 127.0.0.1:8848

#\u8FDE\u63A5\u6570\u636E\u5E93
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.url=jdbc:mysql://localhost:3306/services?useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#\u903B\u8F91\u5220\u9664
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

#mybatis-plus\u65E5\u5FD7
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#\u5F00\u542F\u4E0B\u5212\u7EBF\u8F6C\u9A7C\u5CF0\u547D\u540D
mybatis-plus.configuration.map-underscore-to-camel-case=true

